---
- hosts: debian-jeremy
  become: true
  tasks:
   - name: prepare for install wordpress
     apt:
      update_cache: yes
      name: 
       - apache2
       - mariadb-server
       - python-mysqldb
       - php
       - libapache2-mod-php
       - php-mysql
      state: latest
   - name: create mysql database and restart apache2
     mysql_db:
      name: "{{ wpdname }}"    
   - name: create db user
     mysql_user:
      name: "{{ wpduser }}"
      password: "{{ wpdpass }}"
      priv: '{{ wpdname }}.*:ALL'
      state: present
     ignore_errors: yes
   - name: restart apache  
     service:
      name: apache2
      enabled: yes
   - name: download wordpress
     get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/latest.tar.gz
   - name: Extract wordpress
     become: true
     shell: "tar xvzf /var/www/html/latest.tar.gz"
   - name: set permissions
     file:
      path: /var/www/html/wordpress
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
   - name: change the wp-config-sample.php to wp-config.php and move to right root dir so we cna edit
     command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php 
     become: yes
     ignore_errors: yes
   - name: update wordpress config file 
     lineinfile: 
      path: /var/www/html/wordpress/wp-config.php
      regexp: "{{item.regexp}}" 
      line: "{{item.line}}"
     with_items:
      - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{ wpdname }}' );"}
      - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{ wpduser }}' );"}
      - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{ wpdpass }}' );"}
   - name: restart apache2
     service:
      name: apache2
      state: restarted
